# Generated by Django 3.1.7 on 2021-03-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.FileField(upload_to='Testimonial/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='document',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='document',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone',
        ),
        migrations.AddField(
            model_name='team',
            name='designation',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
