# Generated by Django 3.1.7 on 2021-03-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_auto_20210313_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(default='asd@yahoo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
