# Generated by Django 3.1.7 on 2021-03-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_auto_20210313_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus', models.TextField(max_length=500)),
                ('whatwedo', models.TextField(max_length=500)),
                ('technicalevents', models.TextField(max_length=500)),
                ('culturalevents', models.TextField(max_length=500)),
                ('socialevents', models.TextField(max_length=500)),
                ('talkshows', models.TextField(max_length=500)),
                ('events', models.TextField(max_length=500)),
                ('meettheteam', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=30)),
            ],
        ),
    ]
