# Generated by Django 3.1.7 on 2021-03-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_content_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
