# Generated by Django 3.1.7 on 2021-03-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
