# Generated by Django 3.2.3 on 2021-05-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_auto_20210522_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
