# Generated by Django 3.2.3 on 2021-05-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20210522_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
